---
ansible_become: yes
ansible_become_method: sudo
ansible_user: jlejeune
ip_gateway: 192.168.1.1
ip_dns: 192.168.1.50
domain_search: jlejeune.home
users:
  - username: jlejeune
    group: users
    groups: sudo,audio
    comment: Julien LE JEUNE
    shell: /bin/zsh
    uid: 1026
    password: "{{ ansible_become_pass | password_hash('sha512') }}"
