---
- name: Create manifests directory on first master
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: "0644"
  when: ansible_hostname == hostvars[groups['k3s_masters'][0]]['ansible_hostname']

- name: Download vip rbac manifest to first master
  ansible.builtin.get_url:
    url: https://kube-vip.io/manifests/rbac.yaml
    dest: /var/lib/rancher/k3s/server/manifests/vip-rbac.yaml
    owner: root
    group: root
    mode: "0644"
  when: ansible_hostname == hostvars[groups['k3s_masters'][0]]['ansible_hostname']

- name: Copy kube-vip manifest to first master
  ansible.builtin.template:
    src: kube-vip.manifest.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/kube-vip.yaml
    owner: root
    group: root
    mode: "0644"
  when: ansible_hostname == hostvars[groups['k3s_masters'][0]]['ansible_hostname']
