---
creation_rules:
  - path_regex: 'cluster/.*\.sops\.ya?ml$'
    encrypted_regex: '^(data|stringData)$'
    key_groups:
      - age:
          - age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
  - path_regex: 'ansible/.*\.sops\.ya?ml$'
    unencrypted_regex: '^(kind)$'
    key_groups:
      - age:
          - age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
