---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: weave-gitops-charts
  namespace: flux-system
spec:
  interval: 60m
#  type: oci
#  url: oci://ghcr.io/weaveworks/charts
  url: https://github.com/weaveworks/weave-gitops
  ref:
    tag: v0.38.0
  timeout: 3m
