---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cryptpad-config
  namespace: cryptpad
  labels:
    app.kubernetes.io/instance: cryptpad
  annotations:
    reloader.stakater.com/match: "true"
data:
  config.js: |
    module.exports = {
      httpUnsafeOrigin: 'http://pad.${SECRET_DOMAIN}/',
      httpSafeOrigin: 'https://pad.${SECRET_DOMAIN}/',
      filePath: './data/datastore/',
      logLevel: "info",
      logPath: "./data/logs",
      httpSafePort: 3001,
    };
  application_config.js: |
    /*
    * You can override the configurable values from this file.
    * The recommended method is to make a copy of this file (/customize.dist/application_config.js)
      in a 'customize' directory (/customize/application_config.js).
    * If you want to check all the configurable values, you can open the internal configuration file
      but you should not change it directly (/common/application_config_internal.js)
    */
    define(['/common/application_config_internal.js'], function (AppConfig) {
          AppConfig.availablePadTypes =  ["diagram"];

        return AppConfig;
    });
---
apiVersion: v1
kind: Service
metadata:
  name: cryptpad
  namespace: cryptpad
spec:
  selector:
    app.kubernetes.io/instance: cryptpad
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cryptpad-data
  namespace: cryptpad
spec:
  storageClassName: longhorn
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptpad
  namespace: cryptpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: cryptpad
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: cryptpad
    spec:
      securityContext:
        fsGroup: 4001
      restartPolicy: Always
      containers:
        - name: cryptpad
          image: cryptpad/cryptpad:version-2025.9.0
          securityContext:
            runAsUser: 4001
            runAsGroup: 4001
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: ws
              containerPort: 3003
              protocol: TCP
          volumeMounts:
            - name: configmaps
              mountPath: /cryptpad/config
              #subPath: config.js
            - name: data-volume
              mountPath: /cryptpad/data
          env:
            #- name: CPAD_MAIN_DOMAIN
            #  value: pad.${SECRET_DOMAIN}
            #- name: CPAD_SANDBOX_DOMAIN
            #  value: localhost
            - name: CPAD_INSTALL_ONLYOFFICE
              value: no
            - name: CPAD_CONF
              value: /cryptpad/config/config.js
      volumes:
        - name: configmaps
          configMap:
            name: cryptpad-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: cryptpad-data
