---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: photoprism
  name: photoprism-originals
  namespace: photoprism
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: photoprism
  name: photoprism-storage
  namespace: photoprism
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoprism
  namespace: photoprism
  labels:
    app.kubernetes.io/instance: photoprism
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: photoprism
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: photoprism
    spec:
      restartPolicy: Always
      containers:
        - name: photoprism
          image: photoprism/photoprism:231128
          imagePullPolicy: IfNotPresent
          env:
            - name: PHOTOPRISM_DEBUG
              value: "false"
            - name: PHOTOPRISM_DEFAULT_LOCALE
              value: "fr"
            - name: PHOTOPRISM_STORAGE_PATH
              value: /assets/storage
            - name: PHOTOPRISM_IMPORT_PATH
              value: /assets/photos/import
            - name: PHOTOPRISM_EXPORT_PATH
              value: /assets/photos/export
            - name: PHOTOPRISM_ORIGINALS_PATH
              value: /assets/photos/originals
            - name: PHOTOPRISM_HTTP_HOST
              value: 0.0.0.0
            - name: PHOTOPRISM_HTTP_PORT
              value: "2342"
            - name: PHOTOPRISM_SITE_URL
              value: "https://photos.${SECRET_DOMAIN}"
            - name: PHOTOPRISM_HTTP_COMPRESSION
              value: "gzip"
            - name: PHOTOPRISM_PUBLIC
              value: "false"
            - name: PHOTOPRISM_READONLY
              value: "false"
            - name: PHOTOPRISM_EXPERIMENTAL
              value: "false"
            - name: PHOTOPRISM_DISABLE_WEBDAV
              value: "false"
            - name: PHOTOPRISM_DISABLE_SETTINGS
              value: "false"
            - name: PHOTOPRISM_DISABLE_TENSORFLOW
              value: "false"
            - name: PHOTOPRISM_DISABLE_FACES
              value: "false"
            - name: PHOTOPRISM_DISABLE_CLASSIFICATION
              value: "true"
            - name: PHOTOPRISM_DARKTABLE_PRESETS
              value: "false"
            - name: PHOTOPRISM_DETECT_NSFW
              value: "false"
            - name: PHOTOPRISM_UPLOAD_NSFW
              value: "true"
            - name: PHOTOPRISM_SITE_TITLE
              value: "PhotoPrism"
            - name: PHOTOPRISM_SITE_CAPTION
              value: ""
            - name: PHOTOPRISM_SITE_DESCRIPTION
              value: ""
            - name: PHOTOPRISM_SITE_AUTHOR
              value: ""
            - name: PHOTOPRISM_WORKERS
              value: "1"
            - name: PHOTOPRISM_DATABASE_DRIVER
              value: mysql
            - name: PHOTOPRISM_DATABASE_SERVER
              value: photoprism-db
            - name: PHOTOPRISM_THUMB_UNCACHED
              value: "false"
            - name: PHOTOPRISM_THUMB_SIZE
              value: "2048"
          envFrom:
            - secretRef:
                name: photoprism
                optional: false
          ports:
            - containerPort: 2342
              name: http
          volumeMounts:
            - mountPath: /assets/photos/originals
              name: originals
            - mountPath: /assets/storage
              name: photoprism
              subPath: storage
            - mountPath: /assets/photos/import
              name: photoprism
              subPath: import
            - mountPath: /assets/photos/export
              name: photoprism
              subPath: export
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
      volumes:
        - name: originals
          persistentVolumeClaim:
            claimName: photoprism-originals
        - name: photoprism
          persistentVolumeClaim:
            claimName: photoprism-storage
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
---
apiVersion: v1
kind: Service
metadata:
  name: photoprism
  namespace: photoprism
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/instance: photoprism
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: photoprism
  namespace: photoprism
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`photos.${SECRET_DOMAIN}`) && PathPrefix(`/`)"
      middlewares:
        - name: security-header
          namespace: networking
      services:
        - kind: Service
          name: photoprism
          namespace: photoprism
          port: 80
          scheme: http
  tls:
    secretName: "${SECRET_DOMAIN}-tls"
