apiVersion: v1
stringData:
    MARIADB_PASSWORD: ENC[AES256_GCM,data:T0a4vKiXHBT/PlPjBNrAUtMM4/E=,iv:Pv6sIBN3vhtjhX7h0rU13T22BvVJWXLm1d+srbwbwIg=,tag:ort/ROS8DH1GYnziJs9FEw==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:gTIXoGI4BYRxcbvfG9wPH6F87lE=,iv:3lNTnqDGWziKUoTAiEtGL+bEUNWkr8O0h3dhXk4/Q50=,tag:o4BmYw3GefV2SikR19Zqow==,type:str]
kind: Secret
metadata:
    name: photoprism-db
    namespace: photoprism
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTL0wzcEZOSFZzNkhyY0th
            UjlIVzlNSllkL0RIOTlhZUZxalpJZThYS1RFCmxZUFF5QzlrK3BrZ2dkbmkweHlR
            WnZFOFNwSk1UclQ3cmMrU2wwKzhwNFkKLS0tIGdFZitWMHU4QVcvMU4vMUpSTTdD
            UGFMWC9IMmM4K080eEpWS0QvNUNPamsKxkBZUive0HsmdWFJmLf4XYdb7u8ALWOk
            2jUyV8/dkmi3sl2zfHbFoEnvJp9v1voL0ABSkgjwGEnGPH4/9IPhwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-06T21:17:04Z"
    mac: ENC[AES256_GCM,data:mq9nXgnrPYkfC9sJUdCCPcl3Z2HleC9qsUNHEIFGyJoETwBR97laKqjdZRVyoEyO0HRk7DwIUrll1XdNfWwpL8Inn4FQsoUQX1Pnq6o+JHyArRoDuAXVyaZVR79JfjDzgUeoqjp/hviZ1q11PU0X3MNWPP9gGzc3sr/wikr/f8c=,iv:2ftyPiyibHrxzro7ZCiM3RKvMVlaviGM+kx9qBTw3H4=,tag:eYocIkyd+J/HrgL2iQrLGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
