---
apiVersion: v1
kind: Service
metadata:
  name: joplin
  namespace: joplin
spec:
  ports:
    - name: joplin
      port: 22300
      targetPort: 22300
  selector:
    app.kubernetes.io/instance: joplin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joplin
  namespace: joplin
  labels:
    app.kubernetes.io/instance: joplin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: joplin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: joplin
    spec:
      restartPolicy: Always
      containers:
        - name: joplin
          image: florider89/joplin-server:2.11.2
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_BASE_URL
              value: "https://joplin.${SECRET_DOMAIN}"
            - name: APP_PORT
              value: "22300"
          envFrom:
            - secretRef:
                name: joplin-db
                optional: false
            - configMapRef:
                name: joplin-db
                optional: false
          ports:
            - containerPort: 22300
              name: joplin-port
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: joplin-http
  namespace: joplin
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: "Host(`joplin.${SECRET_DOMAIN}`) && PathPrefix(`/`)"
      middlewares:
        - name: redirect-https
          namespace: networking
      services:
        - kind: Service
          name: joplin
          namespace: joplin
          port: 22300
          scheme: http
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: joplin-https
  namespace: joplin
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`joplin.${SECRET_DOMAIN}`) && PathPrefix(`/`)"
      middlewares:
        - name: security-header
          namespace: networking
      services:
        - kind: Service
          name: joplin
          namespace: joplin
          port: 22300
          scheme: http
  tls:
    secretName: "${SECRET_DOMAIN}-tls"
---
