---
apiVersion: v1
kind: ConfigMap
metadata:
  name: joplin-db
  namespace: joplin
  annotations:
    reloader.stakater.com/match: "true"
data:
  PGDATA: "/var/lib/postgresql/data/pgdata"
  POSTGRES_DATABASE: joplin
  POSTGRES_USER: joplin
  POSTGRES_HOST: joplin-db
  POSTGRES_PORT: "5432"
  DB_CLIENT: pg
---
apiVersion: v1
kind: Service
metadata:
  name: joplin-db
  namespace: joplin
spec:
  ports:
    - name: joplin-db
      port: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/instance: joplin-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: joplin-db-pv
  namespace: joplin
spec:
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '2'
      staleReplicaTimeout: '2880'
    volumeHandle: joplin-db-pv  # we have to create it manually on longhorn UI first
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joplin-db-pvc
  namespace: joplin
spec:
  storageClassName: longhorn
  volumeName: joplin-db-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joplin-db
  namespace: joplin
  labels:
    app.kubernetes.io/instance: joplin-db
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: joplin-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: joplin-db
    spec:
      restartPolicy: Always
      containers:
        - name: joplin-db
          image: postgres:15.8
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: joplin-db
                optional: false
            - configMapRef:
                name: joplin-db
                optional: false
          ports:
            - containerPort: 5432
              name: joplin-db
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: joplin-db-vol
      volumes:
        - name: joplin-db-vol
          persistentVolumeClaim:
            claimName: joplin-db-pvc
---
