---
apiVersion: v1
kind: Service
metadata:
  name: joplin
  namespace: joplin
spec:
  ports:
    - name: joplin
      port: 22300
      targetPort: 22300
  selector:
    app.kubernetes.io/instance: joplin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joplin
  namespace: joplin
  labels:
    app.kubernetes.io/instance: joplin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: joplin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: joplin
    spec:
      restartPolicy: Always
      containers:
        - name: joplin
          image: joplin/server:3.4.3
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_BASE_URL
              value: "https://joplin.${SECRET_DOMAIN}"
            - name: APP_PORT
              value: "22300"
            - name: MAILER_ENABLED
              value: "1"
            - name: MAILER_HOST
              value: "${LB_SMTP_RELAY_ADDRESS}"
            - name: MAILER_PORT
              value: "25"
            - name: MAILER_SECURITY
              value: "none"
            - name: MAILER_NOREPLY_NAME
              value: "Jlejeune Joplin Server"
            - name: MAILER_NOREPLY_EMAIL
              value: "${SECRET_JOPLIN_NOREPLY_EMAIL}"
            - name: LDAP_1_ENABLED
              value: "true"
            - name: LDAP_1_USER_AUTO_CREATION
              value: "true"
            - name: LDAP_1_HOST
              value: "ldap://${NAS_ADDRESS}"
            - name: LDAP_1_MAIL_ATTRIBUTE
              value: "mail"
            - name: LDAP_1_FULLNAME_ATTRIBUTE
              value: "gecos"
            - name: LDAP_1_BASE_DN
              value: "dc=jlejeune,dc=home"
            - name: LDAP_1_BIND_DN
              value: "${SECRET_LDAP_ADMIN_BIND_DN}"
            - name: LDAP_1_BIND_PW
              value: "${SECRET_LDAP_ADMIN_QUERY_PASSWORD}"
          envFrom:
            - secretRef:
                name: joplin-db
                optional: false
            - configMapRef:
                name: joplin-db
                optional: false
          ports:
            - containerPort: 22300
              name: joplin-port
