---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole
  namespace: networking
  annotations:
    reloader.stakater.com/match: "true"
data:
  TZ: "${TZ}"
  ADMIN_EMAIL: "${SECRET_EMAIL}"
  VIRTUAL_HOST: "pihole.${SECRET_DOMAIN}"
  PIHOLE_DNS_: "${NAS_ADDRESS}"
  QUERY_LOGGING: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
  namespace: networking
spec:
  storageClassName: longhorn
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: networking
  labels:
    app.kubernetes.io/instance: pihole
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: pihole
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: pihole
    spec:
      restartPolicy: Always
      containers:
        - name: pihole
          image: pihole/pihole:2025.11.1
          envFrom:
            - configMapRef:
                name: pihole
            - secretRef:
                name: pihole
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole-etc
      volumes:
        - name: pihole-etc
          persistentVolumeClaim:
            claimName: pihole-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-dns-tcp
  namespace: networking
  annotations:
    metallb.io/allow-shared-ip: pihole
    metallb.io/loadBalancerIPs: "${LB_PIHOLE_ADDRESS}"
spec:
  selector:
    app.kubernetes.io/instance: pihole
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-udp
  namespace: networking
  annotations:
    metallb.io/allow-shared-ip: pihole
    metallb.io/loadBalancerIPs: "${LB_PIHOLE_ADDRESS}"
spec:
  selector:
    app.kubernetes.io/instance: pihole
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-dashboard
  namespace: networking
spec:
  selector:
    app.kubernetes.io/instance: pihole
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
