apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: authelia
    namespace: authelia
stringData:
    JWT_TOKEN: ENC[AES256_GCM,data:W4xRYV4I7kYpsCh2JbmAl04V23u7Wkl83ap40cBcAM9ZhMJdvTnoga00TQS5TyrfwRH0Otogzb1QfXIs1q4VSQ==,iv:VxzFVbZXQ/w/xUJtjfA7mhfMx5Sjj+l/fTZqStgyD04=,tag:EGbcA6TT72p9fTQy5RK1Bg==,type:str]
    SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:fkEsK5lyWeU88B5kzdZGAxG58Yym5IuPqzbVC7HI5da0MMKN3Xz5/9wlB1lvf7xM8xii5pQYCqdrh6rehsEvHw==,iv:PO4Hn2v8tINHtQVHPpzxFC4e+kzAmZi1iUkPZW7ppys=,tag:FRUcQF/dFIBudflEyEn1uA==,type:str]
    STORAGE_PASSWORD: ENC[AES256_GCM,data:MwzPagt6BzX2QHhp50vhMbdzWsM=,iv:Vm3ta/L8iNqcsKyaW58cIhNgs3gmPBh/KG6a2LAKPBw=,tag:CrN9oQ8xatj9/GIZPEdhew==,type:str]
    STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:P2wCMiNCiqSBXAuxMx1VdacfttMngl6Lfbfx8LT56EV7mVB8rjbVlqUEjQEqmEv6cvPhLrWjps5lcbiJCWf+rw==,iv:m4mVFUoavwHQ0OHPd9ULB6GSu4R88TiPHaW4h3ewjRg=,tag:y6TafbspYc9VTMubeU+soA==,type:str]
    LDAP_PASSWORD: ENC[AES256_GCM,data:lYvx5qRaTK5rkSXWAmxrsjOUVtmiX0MOWQ==,iv:56Fftp5SC6rYIjMDqYriE3SDbJJ3KTCuCidJbiGqrwo=,tag:cNHE6s5hluQogwzEVVb80g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMktxTkw0eXR6NDRDQmxq
            bUg2UjBxRDhDTURzeEZSUmtIcGE0LytqZWtFClJhRzBHLzkySEdraEpnWlpSZTMy
            LzdjQVlia2ZaamlyS2FrenpNZjFIVmcKLS0tIEt4dVorcHppVnBYN1BmOVNUZW5G
            RE9zV2NKUUkyVXdNLzVXMDJWWFZoVjgKadL+eRiNrjtZRCWGVG7kuRgwHMHVncmj
            DzajZ/0wMCVEFGwM/39PfAKEiUw+OmMEDcn4qpJFp61EL5U4DcWmsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-21T20:21:37Z"
    mac: ENC[AES256_GCM,data:clP9+oBAq0CPPgJLU7I556I1CYrCSkPAfFFfW/c4I0D4we8KG+ATnDGLb9kAHx8BnpzS0eM9iEZYv2IerfKcfj04LYevFFrtUsLoFzAgVNGxMRN+If2E5yR8ZC/6EBUvpk57EG/G8W5OlwV5s9N47+tXo2EHmzq0znWCFgwr3dM=,iv:LlyUaGDvOIytWWvYrHdQpcgslx92DcyCsYRq1xbd9SE=,tag:ON4VvdqnPEIm6ugyT5D0Ng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
