---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-db
  namespace: authelia
  annotations:
    reloader.stakater.com/match: "true"
data:
  PGDATA: "/var/lib/postgresql/data/pgdata"
  POSTGRES_DATABASE: authelia
  POSTGRES_USER: authelia
  POSTGRES_HOST: authelia-db
  POSTGRES_PORT: "5432"
  DB_CLIENT: pg
---
apiVersion: v1
kind: Service
metadata:
  name: authelia-db
  namespace: authelia
spec:
  ports:
    - name: authelia-db
      port: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/instance: authelia-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authelia-db-pv
  namespace: authelia
spec:
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '2'
      staleReplicaTimeout: '2880'
    volumeHandle: authelia-db-pv  # we have to create it manually on longhorn UI first
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-db-pvc
  namespace: authelia
spec:
  storageClassName: longhorn
  volumeName: authelia-db-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia-db
  namespace: authelia
  labels:
    app.kubernetes.io/instance: authelia-db
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: authelia-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: authelia-db
    spec:
      restartPolicy: Always
      containers:
        - name: authelia-db
          image: postgres:15.8
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: authelia-db
                optional: false
            - configMapRef:
                name: authelia-db
                optional: false
          ports:
            - containerPort: 5432
              name: authelia-db
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: authelia-db-vol
      volumes:
        - name: authelia-db-vol
          persistentVolumeClaim:
            claimName: authelia-db-pvc
---
