---
apiVersion: v1
kind: Service
metadata:
  name: authelia-redis
  namespace: authelia
spec:
  ports:
    - name: authelia-redis
      port: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/instance: authelia-redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-redis-config
  namespace: authelia
  annotations:
    reloader.stakater.com/match: "true"
data:
  redis-config: |
    maxmemory 500mb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia-redis
  namespace: authelia
  labels:
    app.kubernetes.io/instance: authelia-redis
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: authelia-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: authelia-redis
    spec:
      restartPolicy: Always
      containers:
        - name: authelia-redis
          image: redis:7.4.0
          command:
            - redis-server
            - "/redis-master/redis.conf"
          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
            - mountPath: /redis-master
              name: config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: authelia-redis-config
            items:
              - key: redis-config
                path: redis.conf
---
