---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
    name: default
    namespace: networking
spec:
    addresses:
        - 192.168.1.200-192.168.1.250
    autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
    name: l2advertisement
    namespace: networking
spec:
    ipAddressPools:
        - default
