---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  ports:
    - name: home-assistant
      port: 80
      targetPort: 8123
  selector:
    app.kubernetes.io/instance: home-assistant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-automation
  labels:
    app.kubernetes.io/instance: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: home-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: homeassistant/home-assistant:2024.4
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "${TZ}"
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1Gi"
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: /config
              name: home-assistant-vol
            - mountPath: /run/dbus
              name: dbus
              readOnly: true
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
      hostNetwork: true
      volumes:
        - name: home-assistant-vol
          persistentVolumeClaim:
            claimName: home-assistant-pvc
        - name: dbus
          hostPath:
            path: /run/dbus
            type: Directory
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pvc
  namespace: home-automation
spec:
  storageClassName: longhorn
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`ha.${SECRET_DOMAIN}`) && PathPrefix(`/`)"
      middlewares:
        - name: forwardauth-authelia
          namespace: networking
        - name: security-header
          namespace: networking
      services:
        - kind: Service
          name: home-assistant
          namespace: home-automation
          port: 80
          scheme: http
  tls:
    secretName: "${SECRET_DOMAIN}-tls"
