---
- name: Set the hostname
  become: yes
  command: hostnamectl set-hostname {{ system_hostname }}

- name: Update /etc/hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1{{'\t'}}{{ system_hostname }}"
    state: present
