---
- name: Configure static IP in /etc/dhcpcd.conf
  become: yes
  lineinfile:
    dest: /etc/dhcpcd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "^interface eth[0-9]$", line: "interface eth0" }
    - { regexp: "^static ip_address", line: "static ip_address={{ ip_address }}" }
    - { regexp: "^static routers", line: "static routers={{ ip_gateway }}" }
    - { regexp: "^static domain_name_servers", line: "static domain_name_servers={{ ip_dns }}" }
    - { regexp: "^static domain_search", line: "static domain_search={{ domain_search }}" }
  notify: reboot
