---
- name: Rename network interface based on its MAC address
  template:
    src: "eth0.link.j2"
    dest: "/etc/systemd/network/01-eth0.link"
    owner: root
    group: root
    mode: 0644
  notify: systemd-networkd

- name: Configure main wired network interface
  template:
    src: "wired.network.j2"
    dest: "/etc/systemd/network/10-wired.network"
    owner: root
    group: root
    mode: 0644
  notify: systemd-networkd

- name: Configure DNS servers
  lineinfile:
    path: /etc/resolv.conf
    line: "{{ item.key }} {{ item.value }}"
    state: present
  with_items:
    - { key: "nameserver", value: "{{ ip_dns }}" }
    - { key: "search", value: "{{ domain_search }}" }
  notify: systemd-networkd

- name: Disable and stop networking service
  ansible.builtin.systemd:
    name: networking
    enabled: no
    state: stopped

- name: Enable and start systemd-networkd service
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: yes
    state: started
