---
- name: Include specific tasks depending on the architecture
  include_tasks: "{{ ansible_architecture }}_plik.yaml"

- name: Copy plikrc config file for root user
  ansible.builtin.template:
    src: plikrc.j2
    dest: /root/.plikrc
    owner: root
    group: root
    mode: '0600'

- name: Copy plikrc config file for all users
  ansible.builtin.template:
    src: plikrc.j2
    dest: "/home/{{ item.username }}/.plikrc"
    owner: "{{ item.username }}"
    group: "{{ item.group }}"
    mode: '0600'
  with_items: "{{ users }}"
