---
- name: Create users accounts
  ansible.builtin.user:
    name: "{{ item.username }}"
    comment: "{{ item.comment }}"
    shell: /bin/zsh
    password: "{{ item.password }}"
    append: yes
    group: "{{ item.group }}"
    groups: "{{ item.groups }}"
    uid: "{{ item.uid }}"
    update_password: on_create
  with_items: "{{ users }}"

- name: Get my dotfiles config
  ansible.builtin.git:
    repo: "https://github.com/jlejeune/dotbot.git"
    dest: "/home/{{ item.username }}/dotbot"
    update: yes
  become: yes
  become_user: "{{ item.username }}"
  with_items: "{{ users }}"

- name: Install my dotfiles
  ansible.builtin.command: "/home/{{ item.username }}/dotbot/install"
  become: yes
  become_user: "{{ item.username }}"
  with_items: "{{ users }}"

- name: Remove the user 'pi'
  ansible.builtin.user:
    name: pi
    state: absent
    remove: yes
