---
- name: Create users accounts
  ansible.builtin.user:
    name: "{{ item.username }}"
    comment: "{{ item.comment }}"
    shell: /bin/zsh
    password: "{{ item.password }}"
    append: yes
    group: "{{ item.group }}"
    groups: "{{ item.groups }}"
    uid: "{{ item.uid }}"
    update_password: on_create
  with_items: "{{ users }}"

- name: Get my dotfiles config for me and for root user
  ansible.builtin.git:
    repo: "https://github.com/jlejeune/dotbot.git"
    dest: "{{ item.home }}/.dotbot"
    update: yes
  become: yes
  become_user: "{{ item.username }}"
  with_items:
    - { username: "jlejeune", home: "/home/jlejeune" }
    - { username: "root", home: "/root" }

- name: Install my dotfiles for me and for root user
  ansible.builtin.command: "{{ item.home }}/.dotbot/install"
  become: yes
  become_user: "{{ item.username }}"
  with_items:
    - { username: "jlejeune", home: "/home/jlejeune" }
    - { username: "root", home: "/root" }

- name: Remove the user 'pi'
  ansible.builtin.user:
    name: pi
    state: absent
    remove: yes
