---
- name: Download plik binary amd64
  get_url:
    url: "https://github.com/root-gg/plik/releases/download/{{ plik_version }}/plik-{{ plik_version }}-linux-amd64.tar.gz"
    dest: /tmp

- name: Extract plik archive
  ansible.builtin.unarchive:
    src: "/tmp/plik-{{ plik_version }}-linux-amd64.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Move plik binary to /usr/local/bin/ folder
  command: mv /tmp/plik-{{ plik_version }}-linux-amd64/clients/linux-386/plik /usr/local/bin/plik
