---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-external-provisioner
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner
      tag: v4.0.2
    nfs:
      server: "${NAS_ADDRESS}"
      path: "/volume1/k3s"
    storageClass:
      name: nfs
      defaultClass: false
      archiveOnDelete: false
