---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/kubernetes-sigs/node-feature-discovery/v0.14.0/deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
