---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: home-automation
  labels:
    app.kubernetes.io/instance: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.18
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8883
              name: mqtts
              protocol: TCP
            - containerPort: 9002
              name: mqttwebsocket
              protocol: TCP
          volumeMounts:
            - mountPath: /mosquitto/config/
              name: config
            - mountPath: /mosquitto/certs/
              name: certs
            - mountPath: /mosquitto/data/
              name: data
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9002
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9002
            timeoutSeconds: 1
      volumes:
        - name: config
          configMap:
            name: mosquitto
        - name: certs
          secret:
            secretName: mosquitto-certs
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data-pvc
  namespace: home-automation
spec:
  storageClassName: longhorn
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: home-automation
  annotations:
    metallb.universe.tf/loadBalancerIPs: ${LB_MQTT_ADDRESS}
spec:
  type: LoadBalancer
  ports:
    - port: 8883
      protocol: TCP
      targetPort: mqtts
      name: mqtts
  selector:
    app.kubernetes.io/instance: mosquitto
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto
  namespace: home-automation
data:
  mosquitto.conf: |
    # Persistence configuration
    persistence true
    persistence_location /mosquitto/data/

    # Logging
    log_type error
    log_type warning
    log_type notice
    log_type information
    log_dest stdout
    log_timestamp true
    log_timestamp_format %Y-%m-%dT%H:%M:%S

    # Listeners
    listener 8883
    protocol mqtt
    certfile /mosquitto/certs/tls.crt
    keyfile /mosquitto/certs/tls.key

    listener 9002
    protocol websockets
    certfile /mosquitto/certs/tls.crt
    keyfile /mosquitto/certs/tls.key

    # Security
    password_file /mosquitto/config/mosquitto.passwd
    acl_file /mosquitto/config/mosquitto.acl
  mosquitto.passwd: |
    homeassistant:$7$101$qhRjwnzNmRpTP54v$mMEma60H9AZtN9S0rUpuvfk54aj37BNw5aOI7snFqhg3MX8vypz3rq8+AcnOzikXw3GV7FYUdqmdXkl46U608g==
    owntracks:$7$101$9oq3A9AHNJRkCsK5$gLzN3cV9k+97iIVWjylc0EgUKz9aQYp+tZ+SOWJigz0I2C6S3Yv1Lb2wkunFmM5mtUiFgUDD5lGuCwzdmrDWXg==
    zigbee2mqtt:$7$101$QKN5Ghmr4QaiXn5A$KB42itqcWqjjghNpkhlZLsEHRo5Yu28Z9HGmQNvu+dMs/Ra/e+zk3XwQyawsdthUYVFhdt29KnMRNMUGpwrXxA==
    roomassistant:$7$101$qbqvFlMcQ/cucKGI$1blNle66cZu+sP7wrHz8ROgj1k6o9/cO26rCViFMbG1PNSy1teQ/et/VGi89Zjk+eorDwDJ+8htRn0XFSfLe/w==
  mosquitto.acl: |
    user homeassistant
    topic readwrite #

    user owntracks
    topic readwrite #

    user zigbee2mqtt
    topic readwrite #

    user roomassistant
    topic readwrite #
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  dnsNames:
    - mqtt.${SECRET_DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: mosquitto-certs
