---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 60m
  # https://github.com/jlejeune/jlejeune.home-ansible
  url: ssh://git@github.com/jlejeune/jlejeune.home-ansible
  ref:
    branch: master
  secretRef:
    name: github-deploy-key
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 60m
  path: ./cluster/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-cluster
