---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go2rtc
  namespace: home-automation
  labels:
    app.kubernetes.io/instance: go2rtc
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: go2rtc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: go2rtc
    spec:
      containers:
        - name: go2rtc
          image: alexxit/go2rtc:1.9.9
          ports:
            - containerPort: 1984
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: config
---
apiVersion: v1
kind: Service
metadata:
  name: go2rtc
  namespace: home-automation
  annotations:
    metallb.io/loadBalancerIPs: ${LB_GO2RTC_ADDRESS}
spec:
  selector:
    app.kubernetes.io/instance: go2rtc
  ports:
    - protocol: TCP
      targetPort: 1984
      port: 1984
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: home-automation
data:
  go2rtc.yaml: |
    streams:
      cam1: rtsp://admin:${SECRET_CAMERA_PASSWORD}@192.168.1.167/Preview_01_main
