---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: networking
  labels:
    app.kubernetes.io/instance: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: wireguard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: wireguard
    spec:
      restartPolicy: Always
      containers:
        - name: wireguard
          image: linuxserver/wireguard:1.0.20250521
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          ports:
            - containerPort: 51820
              protocol: UDP
          env:
            - name: TZ
              value: "{{TZ}}"
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "128Mi"
          volumeMounts:
            - name: wireguard-config
              mountPath: /config/wg0.conf
              subPath: wg0.conf
            - name: host-volumes
              mountPath: /lib/modules
      volumes:
        - name: wireguard-config
          secret:
            secretName: wireguard-config
        - name: host-volumes
          hostPath:
            path: /lib/modules
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: networking
spec:
  selector:
    app.kubernetes.io/instance: wireguard
  ports:
    - port: 51820
      targetPort: 51820
      protocol: UDP
