---
apiVersion: v1
kind: Service
metadata:
  name: smtp-relay
  namespace: smtp-relay
  annotations:
    metallb.universe.tf/loadBalancerIPs: ${LB_SMTP_RELAY_ADDRESS}
spec:
  type: LoadBalancer
  ports:
    - name: smtp
      targetPort: 25
      port: 25
      protocol: TCP
  selector:
    app.kubernetes.io/instance: smtp-relay
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smtp-relay-pvc
  namespace: smtp-relay
spec:
  storageClassName: longhorn
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp
  namespace: smtp-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: smtp-relay
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: smtp-relay
    spec:
      containers:
        - name: smtp
          image: juanluisbaptiste/postfix:1.7.1
          ports:
            - containerPort: 25
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: smtp-relay
          volumeMounts:
            - name: data
              mountPath: /var/spool/postfix
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: smtp-relay-pvc
