---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-pv
  namespace: freshrss
spec:
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '2'
      staleReplicaTimeout: '20'
    volumeHandle: freshrss-pv  # we have to create it manually on longhorn UI first
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-pvc
  namespace: freshrss
spec:
  storageClassName: longhorn
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
  namespace: freshrss
  labels:
    app.kubernetes.io/instance: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: freshrss
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: freshrss
    spec:
      restartPolicy: Always
      containers:
        - name: freshrss
          image: lscr.io/linuxserver/freshrss:1.28.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "${TZ}"
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /config
              name: freshrss-vol
      volumes:
        - name: freshrss-vol
          persistentVolumeClaim:
            claimName: freshrss-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: freshrss
  namespace: freshrss
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/instance: freshrss
