---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piper-pvc
  namespace: home-automation
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper
  namespace: home-automation
  labels:
    app.kubernetes.io/instance: piper
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: piper
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: piper
    spec:
      containers:
        - name: piper
          image: rhasspy/wyoming-piper:1.6.3
          args:
            - --voice
            - fr_FR-upmc-medium
          env:
            - name: TZ
              value: "${TZ}"
          ports:
            - name: piper
              containerPort: 10200
              protocol: TCP
          volumeMounts:
            - name: piper-data
              mountPath: /data
      volumes:
        - name: piper-data
          persistentVolumeClaim:
            claimName: piper-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: piper
  namespace: home-automation
  annotations:
    metallb.io/loadBalancerIPs: ${LB_PIPER_ADDRESS}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: piper
  ports:
    - protocol: TCP
      name: piper
      port: 10200
      targetPort: 10200
