---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 60m
  chart:
    spec:
      chart: longhorn
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 60m
  values:
    metrics:
      serviceMonitor:
        enabled: true
    persistence:
      defaultClass: false
      defaultClassReplicaCount: "2"
    defaultSettings:
      defaultReplicaCount: "2"
      defaultDataPath: "/storage"
      backupTarget: "nfs://${NAS_ADDRESS}:/volume1/k3s/longhorn_backup"
      replicaSoftAntiAffinity: true
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
