---
systemd_dir: /etc/systemd/system

# k3s
k3s_master_vip: 192.168.1.9
vip_interface: eth0

extra_args: "--node-ip={{ ansible_facts['eth0']['ipv4']['address'] }}"

k3s_master_init_args: >-
  {% if ansible_hostname == hostvars[groups['k3s_masters'][0]]['ansible_hostname'] -%}
    --cluster-init
  {%- else -%}
    --server https://{{ k3s_master_vip }}:6443
  {%- endif -%}

k3s_master_taint: "{{ true if groups['k3s_workers'] | default([]) | length >= 1 else false }}"

k3s_master_extra_args: >-
  {{ extra_args }}
  {{ k3s_master_init_args }}
  --token {{ hostvars[groups['k3s_masters'][0]]['token'] | default (k3s_token) }}
  --tls-san={{ k3s_master_vip }}
  {{ '--node-taint node-role.kubernetes.io/master=true:PreferNoSchedule' if k3s_master_taint else '' | trim }}
  --disable servicelb
  --disable traefik
  --write-kubeconfig-mode 644
  --kube-apiserver-arg default-not-ready-toleration-seconds=30
  --kube-apiserver-arg default-unreachable-toleration-seconds=30
  --kube-controller-arg node-monitor-period=20s
  --kube-controller-arg node-monitor-grace-period=20s
  --kubelet-arg node-status-update-frequency=5s

# k9s
k9s_version: v0.40.10

# helm
helm_version: v3.9.3

# sops
sops_version: v3.7.3
