---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-db
  namespace: immich
data:
  PGDATA: "/var/lib/postgresql/data/pgdata"
  POSTGRES_DATABASE: immich
  POSTGRES_USER: immich
  POSTGRES_HOST: immich-db
  POSTGRES_PORT: "5432"
  DB_CLIENT: pg
---
apiVersion: v1
kind: Service
metadata:
  name: immich-db
  namespace: immich
spec:
  ports:
    - name: immich-db
      port: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/instance: immich-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-db-pv
  namespace: immich
spec:
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '2'
      staleReplicaTimeout: '2880'
    volumeHandle: immich-db-pv  # we have to create it manually on longhorn UI first
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-db-pvc
  namespace: immich
spec:
  storageClassName: longhorn
  volumeName: immich-db-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: immich-db
  name: immich-db
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: immich-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: immich-db
    spec:
      restartPolicy: Always
      containers:
        - name: immich-db
          image: tensorchord/pgvecto-rs:pg15-v0.1.11
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: immich-db
                optional: false
            - configMapRef:
                name: immich-db
                optional: false
          ports:
            - containerPort: 5432
              name: immich-db
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: immich-db-vol
      volumes:
        - name: immich-db-vol
          persistentVolumeClaim:
            claimName: immich-db-pvc
---
