---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-typesense
  namespace: immich
  labels:
    app.kubernetes.io/instance: immich-typesense
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: immich-typesense
  namespace: immich
  labels:
    app.kubernetes.io/instance: immich-typesense
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: immich-typesense
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: immich-typesense
    spec:
      containers:
        - name: immich-typesense
          image: "typesense/typesense:0.25.1"
          ports:
            - containerPort: 8108
          env:
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: immich
                  key: TYPESENSE_API_KEY
            - name: TYPESENSE_DATA_DIR
              value: "/data"
          volumeMounts:
            - name: tsdata
              mountPath: /data
      volumes:
        - name: tsdata
          persistentVolumeClaim:
            claimName: immich-typesense
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
---
kind: Service
apiVersion: v1
metadata:
  name: immich-typesense
  namespace: immich
  labels:
    app.kubernetes.io/instance: immich-typesense
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: immich-typesense
  ports:
    - port: 8108
      targetPort: 8108
      protocol: TCP
