---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: immich-microservice
  namespace: immich
  labels:
    app.kubernetes.io/instance: immich-microservice
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: immich-microservice
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: immich-microservice
    spec:
      initContainers:
        - name: postgresql-isready
          image: postgres:15.5
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: immich
                  key: DB_USERNAME
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: immich
                  key: DB_DATABASE_NAME
          command:
            - /bin/sh
            - -c
            - until pg_isready -U "${POSTGRES_USER}" -d
              "dbname=${POSTGRE_DB}" -h immich-db -p 5432 ; do
              sleep 2 ; done
      containers:
        - name: immich-microservice
          image: altran1502/immich-server:v1.98.1
          command:
            - /bin/sh
          args:
            - ./start-microservices.sh
          env:
            - name: NODE_ENV
              value: "production"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich
                  key: DB_PASSWORD
          envFrom:
            - configMapRef:
                name: immich
                optional: false
          volumeMounts:
            - name: geodata-cache
              mountPath: /geodata-cache
            - name: library
              mountPath: /usr/src/app/upload
            - name: jlejeune-library
              mountPath: /usr/src/app/upload/library/jlejeune
            - name: aconvert-library
              mountPath: /usr/src/app/upload/library/aconvert
          resources: {}
      volumes:
        - name: geodata-cache
          emptyDir: {}
        - name: library
          persistentVolumeClaim:
            claimName: immich-library-pvc
        - name: jlejeune-library
          persistentVolumeClaim:
            claimName: immich-jlejeune-library-pvc
        - name: aconvert-library
          persistentVolumeClaim:
            claimName: immich-aconvert-library-pvc
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
