---
apiVersion: v1
kind: Service
metadata:
  name: immich-redis
  namespace: immich
spec:
  ports:
    - name: immich-redis
      port: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/instance: immich-redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-redis-config
  namespace: immich
  annotations:
    reloader.stakater.com/match: "true"
data:
  redis-config: |
    maxmemory 500mb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-redis
  namespace: immich
  labels:
    app.kubernetes.io/instance: immich-redis
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: immich-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: immich-redis
    spec:
      restartPolicy: Always
      containers:
        - name: immich-redis
          image: redis:7.4.5
          command:
            - redis-server
            - "/redis-master/redis.conf"
          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
            - mountPath: /redis-master
              name: config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: immich-redis-config
            items:
              - key: redis-config
                path: redis.conf
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
---
