---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - immich-db.secret.sops.yaml
  - immich-db.yaml
  - immich-config.yaml
  - immich-machine-learning.yaml
  - immich-microservice.yaml
  - immich-redis.yaml
  - immich.secret.sops.yaml
  - immich-server.yaml
