---
- name: Delete k3s if already present
  ansible.builtin.file:
    path: /usr/local/bin/k3s
    state: absent

- name: Download k3s binary
  ansible.builtin.get_url:
    url: "https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s-arm64"
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: '0755'
