---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: home-automation
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: home-automation
  labels:
    app.kubernetes.io/instance: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ollama
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:0.11.4
          env:
            - name: HOME
              value: /home/ollama
          ports:
            - name: http
              containerPort: 11434
              protocol: TCP
          volumeMounts:
            - name: ollama-data
              mountPath: /home/ollama/.ollama
          tty: true
      nodeSelector:
        feature.node.kubernetes.io/custom-zigbee: "true"
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: home-automation
  annotations:
    metallb.io/loadBalancerIPs: ${LB_OLLAMA_ADDRESS}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: ollama
  ports:
    - port: 11434
      name: ollama
      targetPort: 11434
      protocol: TCP
