---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-ovh
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: deploy/cert-manager-webhook-ovh
      version: 0.3.0
      sourceRef:
        kind: GitRepository
        name: cert-manager-webhook-ovh-charts
        namespace: flux-system
  values:
    groupName: "${SECRET_DOMAIN}"
