---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security-header
  namespace: networking
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    forceSTSHeader: true
    referrerPolicy: same-origin
    customResponseHeaders:
      permissions-Policy: vibrate=(self), geolocation=(self), midi=(self), notifications=(self), push=(self), microphone=(), $
      X-Permitted-Cross-Domain-Policies: none
      expect-ct: max-age=604800, report-uri="https://oak.ct.letsencrypt.org/2021"
