---
- name: Download k3s
  hosts: k3s_cluster
  become: yes
  roles:
    - k3s

- name: Configure k3s master
  hosts: k3s_master
  become: yes
  roles:
    - k3s/master

- name: Configure k3s workers
  hosts: k3s_workers
  become: yes
  roles:
    - k3s/worker

- name: Define k3s workers role
  hosts: k3s_master
  become: yes
  tasks:
    - ansible.builtin.command: >-
        kubectl label nodes {{ item }} kubernetes.io/role=worker --overwrite
      with_items: "{{ groups.k3s_workers }}"
