---
- name: Patch Flux branch
  hosts: k3s_masters
  gather_facts: no
  become: yes
  vars:
    is_first_master: ansible_hostname == hostvars[groups['k3s_masters'][0]]['ansible_hostname']

  tasks:
    - name: Test if branch variable is defined
      fail:
        msg: "variable {{ branch }} is required"
      when: not branch and is_first_master

    - name: Disable automatic sync
      ansible.builtin.command: flux suspend kustomization flux-cluster
      when: is_first_master

    - name: Patch flux-cluster repository branch
      ansible.builtin.command: kubectl patch gitrepo/flux-cluster -n flux-system --type merge --patch "{\"spec\":{\"ref\":{\"branch\":\"{{ branch }}\"}}}"
      when: is_first_master

    - name: Manually sync the config
      ansible.builtin.command: flux reconcile kustomization apps
      ignore_errors: yes
      when: is_first_master
