---
- name: Patch Flux branch
  hosts: k3s_master
  gather_facts: no
  become: yes

  tasks:
  - name: Test if branch variable is defined
    fail:
      msg: "variable {{ branch }} is required"
    when: not branch

  - name: Disable automatic sync
    ansible.builtin.command: flux suspend kustomization flux-cluster

  - name: Patch flux-cluster repository branch
    ansible.builtin.command: kubectl patch gitrepo/flux-cluster -n flux-system --type merge --patch "{\"spec\":{\"ref\":{\"branch\":\"{{ branch }}\"}}}"

  - name: Manually sync the config
    ansible.builtin.command: flux reconcile kustomization apps
    no_log: True
