---
- name: Revert Flux branch
  hosts: k3s_masters
  gather_facts: no
  become: yes
  vars:
    is_first_master: ansible_hostname == hostvars[groups['k3s_masters'][0]]['ansible_hostname']

  tasks:
    - name: Resume automatic sync
      ansible.builtin.command: flux resume kustomization flux-cluster
      when: is_first_master
