---
- hosts: k3s_workers
  become: yes
  tasks:
  - name: Uninstall k3s
    shell: /usr/local/bin/k3s-agent-uninstall.sh

- hosts: k3s_master
  become: yes
  tasks:
  - name: Uninstall k3s
    shell: /usr/local/bin/k3s-uninstall.sh
