---
- name: Upgrade flux
  hosts: k3s_masters
  gather_facts: no
  become: yes
  vars:
    is_first_master: ansible_hostname == hostvars[groups['k3s_masters'][0]]['ansible_hostname']

  tasks:
    - name: Copy cluster config
      ansible.builtin.copy:
        src: ../../cluster
        dest: /root
        owner: root
        group: root
        mode: 0755
      when: is_first_master

    - name: Upgrade flux cli
      ansible.builtin.shell: curl -s https://fluxcd.io/install.sh | bash
      when: is_first_master

    - name: Delete previous flux components
      ansible.builtin.shell: kubectl delete all --all -n flux-system
      when: is_first_master

    - name: Install new flux components
      ansible.builtin.shell: flux install --export | kubectl apply -f -
      when: is_first_master

    - name: Deploy flux config
      ansible.builtin.command: kubectl apply --kustomize /root/cluster/flux/flux-system/
      when: is_first_master
