---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 15m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery-charts
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    enableNodeFeatureApi: true
    worker:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      config:
        core:
          sources:
            - custom
            - usb
        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "03"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - class
              - vendor
              - device
          custom:
            - name: zigbee
              matchOn:
                - usbId:
                    class: ["ff"]
                    vendor: ["10c4"]
                    device: ["ea60"]
