---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 15m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.16.1
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery-charts
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    enableNodeFeatureApi: true
    worker:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      config:
        core:
          sources:
            - custom
            - usb
        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "03"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - class
              - vendor
              - device
          custom:
            - name: zigbee
              labels:
                custom-zigbee: "true"
              matchFeatures:
                - feature: usb.device
                  matchExpressions:
                    class: {op: In, value: ["ff"]}
                    vendor: {op: In, value: ["10c4"]}
                    device: {op: In, value: ["ea60"]}
            - name: bluetooth
              labels:
                custom-bluetooth: "true"
              matchFeatures:
                - feature: usb.device
                  matchExpressions:
                    class: {op: In, value: ["ff"]}
                    vendor: {op: In, value: ["0bda"]}
                    device: {op: In, value: ["0129"]}
