---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          webhook:
            groupName: "${DOMAIN}"
            solverName: ovh
            config:
              endpoint: ovh-eu
              applicationKey: 4dcbfd3b80e635c8
              applicationSecretRef:
                key: ovh_application_secret
                name: issuers
              consumerKey: 0d1bbe46335ebb66d5e2959d7a15640f
        selector:
          dnsZones:
            - "${DOMAIN}"
