---
systemd_dir: /etc/systemd/system

# k3s
k3s_master_vip: 192.168.1.9
extra_args: "--node-ip={{ ansible_facts['eth0']['ipv4']['address'] }}"

k3s_worker_extra_args: >-
  {{ extra_args }}
  --server https://{{ k3s_master_vip }}:6443
  --token {{ hostvars[groups['k3s_masters'][0]]['token'] | default (k3s_token) }}
  --kubelet-arg node-status-update-frequency=5s
