---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netalertx-db
  namespace: networking
spec:
  storageClassName: longhorn
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netalertx-config
  namespace: networking
spec:
  storageClassName: longhorn
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netalertx
  namespace: networking
  labels:
    app.kubernetes.io/instance: netalertx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: netalertx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: netalertx
    spec:
      containers:
        - name: netalertx
          image: jokobsk/netalertx:25.4.1
          ports:
            - containerPort: 20211
          env:
            - name: TZ
              value: "${TZ}"
            - name: PORT
              value: "20211"
            - name: HOST_USER_ID
              value: "1000"
            - name: HOST_USER_GID
              value: "1000"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
            - name: db-volume
              mountPath: /app/db
      hostNetwork: true
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: netalertx-config
        - name: db-volume
          persistentVolumeClaim:
            claimName: netalertx-db
---
apiVersion: v1
kind: Service
metadata:
  name: netalertx
  namespace: networking
spec:
  selector:
    app.kubernetes.io/instance: netalertx
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 20211
      targetPort: 20211
