---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 10.24.1
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    image:
      name: ghcr.io/k8s-at-home/traefik
    deployment:
      kind: Deployment
      replicas: 1
    podSecurityPolicy:
      enabled: true
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: "${LB_TRAEFIK_ADDRESS}"
        externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: "traefik"
        metallb.universe.tf/loadBalancerIP: "${LB_TRAEFIK_ADDRESS}"
    logs:
      general:
        format: json
        level: INFO
      access:
        enabled: true
        format: json
    ingressClass:
      enabled: true
      isDefaultClass: true
      fallbackApiVersion: v1
    ingressRoute:
      dashboard:
        enabled: false
    globalArguments:
      - "--api.insecure=true"
      - "--serverstransport.insecureskipverify=true"
      - "--providers.kubernetesingress.ingressclass=traefik"
      - "--metrics.prometheus=false"
      - "--metrics.prometheus.entryPoint=metrics"
    additionalArguments:
      - "--providers.kubernetesingress.ingressendpoint.ip=${LB_TRAEFIK_ADDRESS}"
      - "--providers.kubernetesingress.allowexternalnameservices=true"
      - "--providers.kubernetescrd.allowexternalnameservices=true"
      - "--providers.kubernetescrd.allowCrossNamespace=true"
    ports:
      traefik:
        expose: true
      web:
        address: 80
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
      websecure:
        tls:
          enabled: true
          options: default
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: true
        cipherSuites:
          - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
          - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
          - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
          - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
          - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
          - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
          - TLS_AES_256_GCM_SHA384
          - TLS_AES_128_GCM_SHA256
    pilot:
      enabled: false
    experimental:
      plugins:
        enabled: false
    resources:
      requests:
        memory: 200Mi
        cpu: 500m
      limits:
        memory: 500Mi
