---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 26.1.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    deployment:
      kind: Deployment
      replicas: 1
    podSecurityPolicy:
      enabled: false
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: "${LB_TRAEFIK_ADDRESS}"
        externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: "traefik"
        metallb.universe.tf/loadBalancerIP: "${LB_TRAEFIK_ADDRESS}"
    logs:
      general:
        format: json
        level: INFO
      access:
        enabled: true
        format: json
    ingressClass:
      enabled: true
      isDefaultClass: true
      fallbackApiVersion: v1
    ingressRoute:
      dashboard:
        enabled: false
    globalArguments:
      - "--api.insecure=true"
      - "--serverstransport.insecureskipverify=true"
      - "--providers.kubernetesingress.ingressclass=traefik"
    additionalArguments:
      - "--providers.kubernetesingress.ingressendpoint.ip=${LB_TRAEFIK_ADDRESS}"
      - "--providers.kubernetesingress.allowexternalnameservices=true"
      - "--providers.kubernetescrd.allowexternalnameservices=true"
      - "--providers.kubernetescrd.allowCrossNamespace=true"
    ports:
      traefik:
        expose: true
    entryPoints:
      web:
        address: ":80"
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
      websecure:
        address: ":443"
    tlsOptions:
      default:
        minVersion: VersionTLS12
        sniStrict: true
        cipherSuites:
          - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 # TLS 1.2
          - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305  # TLS 1.2
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384   # TLS 1.2
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305    # TLS 1.2
          - TLS_AES_256_GCM_SHA384                  # TLS 1.3
          - TLS_CHACHA20_POLY1305_SHA256            # TLS 1.3
          - TLS_FALLBACK_SCSV                       # TLS FALLBACK
        curvePreferences:
          - secp521r1
          - secp384r1
    experimental:
      plugins:
        enabled: false
    resources:
      requests:
        memory: 200Mi
        cpu: 500m
      limits:
        memory: 500Mi
