apiVersion: v1
kind: Secret
metadata:
    name: lam-ldap-secret
    namespace: openldap
type: Opaque
stringData:
    LDAP_BASE: ENC[AES256_GCM,data:OtMNxVIT8uNAJtw8l9c4A3Onlg==,iv:7Mfyi6MXr9wXywa1mkztzztLv0sYlJVMBbB3MDCNe8g=,tag:UQHO/XofaU52LgXazACIBg==,type:str]
    LDAP_BINDDN: ENC[AES256_GCM,data:3ClOK1vNY/vAb4sstf06whiTEgelmNU5gY+/8Q==,iv:7py89HatrXwuWeZCiMoS/vSxqNCLFaekzETv3rFLMPM=,tag:gShg1Z6RX01OoztWQvGfyw==,type:str]
    LDAP_PASSWORD: ENC[AES256_GCM,data:Fqyxq1t9s/bhYNdIV0AQwedxFIswOj4bRg==,iv:3dqHr7/eYblhWrmLQIP4WO3z/ya1+m/PmFgCdLi8xWo=,tag:N/TqGACudMm3/r/yfWs7Cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZUg1bVRlNmZoamgvdWE2
            SHRzVlloYU5qemM4aE1VZFRBeVB2MldOWkNNCjh1dXZDbGx0Qyt4RVc4Um1rSjVi
            c1NBaFVMRXdQcUpOZmxuUGVydlp0TWMKLS0tIFNSRW94WitxbmNxc1lCYXh2ejBN
            NXRjYXkvYzZOL0hlR0pmY2F5cWd1Q1EK4QRtywX0z0ZjY85y2E7gRZAbtwJebSjV
            hetjsA47oYjx/9sIOysO4fUzBVma+U+SoSb/OXIli/DbvV4y7KAvOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-25T20:14:16Z"
    mac: ENC[AES256_GCM,data:LJdf5AqapKcGlAtZgOv1g8j1pY1xDTXT8j/rhFZA03urCu40zHmZP1C3vy2QPNyHiMdu4uWxRmgoPqTSBdfM2jSZPfKzZium54jw4k824+IA7ypbv3PkL/Q7+u5xUmILGlNfb9PaUlOGKaeCxJVGMkBWSwsvZJmwNpSZdQivw+o=,iv:SLPyKJXgmHUnvf7659pnaW+N2h1nPCpIv+awRhBvU6A=,tag:azRvbB0ZxE6yY7BoJAYEDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
