apiVersion: v1
data:
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:IuIhLflpgeCR40pAk8lBQLA8ZbaTiJkZYabL0gbREgD1+KKs,iv:4E6ou1whXmO+E3kr6TNkH5pEG1tdB3MZCdJVrcmgs+M=,tag:D7oeP1IuORIjGjxVqJzBlQ==,type:str]
kind: Secret
metadata:
    name: openldap
    namespace: openldap
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT1JWWDFWY0hIM2g3MXBJ
            SVQ2Mkx0WkE2RWwvU3VYRzk5MHBCSFc2SVVVCm9XOFlOUFg0ckhBcmdSeS9KcFZI
            aklDMlJLdG4zNzZyODM4ajdvbFMxRUUKLS0tIGFPWm5sRnhhMFgrVzdVb0M4dnZJ
            dDdKWENNT3pGb3Z1ZmNmRTF6ZUlMVUUKVgb/7zadiU6GYLcFGXB1+/hPMAM0P4Xf
            kPUVGkOroIkJJ+982qSv0rvbDGlP1Off43p6AtsKc5IQ3jdC54D1uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-22T06:57:09Z"
    mac: ENC[AES256_GCM,data:28hM3fxWusAVxEXlK3msmAnQEmxY3IX7l1yEMjHURfKml2m9NiMyzEvpkRO2SUqitoryDxjaXP3LKf3DdjY1QgaJvlZ6syDB02kqOJlSdaJjE18+Z/u+ezSwYE2BmUl0ZGSXjFi/lYaQZat7YlpiJ4KcEyYPRDJg3ztVN52IJ58=,iv:p7sp2xI1YgshqttwaxVg4Ip9V6TOyETZfvgxMGEFVo0=,tag:iqrAwmyJbVeUMKT9KcBhPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
