apiVersion: v1
data:
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:xBtImg==,iv:DSIGa4gMDWxgG0scpuNTaTsyVreW3Lnmw7mOylLTNyo=,tag:1F89E2HTaaquEQs+iIlXsw==,type:str]
kind: Secret
metadata:
    name: openldap
    namespace: openldap
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT1JWWDFWY0hIM2g3MXBJ
            SVQ2Mkx0WkE2RWwvU3VYRzk5MHBCSFc2SVVVCm9XOFlOUFg0ckhBcmdSeS9KcFZI
            aklDMlJLdG4zNzZyODM4ajdvbFMxRUUKLS0tIGFPWm5sRnhhMFgrVzdVb0M4dnZJ
            dDdKWENNT3pGb3Z1ZmNmRTF6ZUlMVUUKVgb/7zadiU6GYLcFGXB1+/hPMAM0P4Xf
            kPUVGkOroIkJJ+982qSv0rvbDGlP1Off43p6AtsKc5IQ3jdC54D1uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-24T19:49:18Z"
    mac: ENC[AES256_GCM,data:qAbehcNNI9EZTV9ygQTE8b0s7WOZ35ceF5g2pO5ys2XBDmUx95/HpLj0L23yXObqSjIOFkH+OZGpzDDk496JFa28FcUKvkqxFnjX65bM43sxdzH9UNOULQt7PGd8kYiesznnys13teGXoB/ngb27QmF0lto1UcJomeMRarORvWg=,iv:0qEdv78qQt5yhdZQ5e6x+q95llXCe8QajCHdiQJ2e0w=,tag:48gOdQqqhdx0z4DSuYa/uA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
