apiVersion: v1
stringData:
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:/2P/FQVVUgNk4LhHgAdpjXeG3SK8Z7LGAw==,iv:YFbsXyj7zcI6rBESy4+I3EiPPUcQ9xCIUaveQS/dupI=,tag:3Kfo4pbb6UpRYkWygaUXDA==,type:str]
#    LDAP_READONLY_USER_PASSWORD: phxT*nX@ce%!4LrYY5xZ
kind: Secret
metadata:
    name: openldap
    namespace: openldap
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT1JWWDFWY0hIM2g3MXBJ
            SVQ2Mkx0WkE2RWwvU3VYRzk5MHBCSFc2SVVVCm9XOFlOUFg0ckhBcmdSeS9KcFZI
            aklDMlJLdG4zNzZyODM4ajdvbFMxRUUKLS0tIGFPWm5sRnhhMFgrVzdVb0M4dnZJ
            dDdKWENNT3pGb3Z1ZmNmRTF6ZUlMVUUKVgb/7zadiU6GYLcFGXB1+/hPMAM0P4Xf
            kPUVGkOroIkJJ+982qSv0rvbDGlP1Off43p6AtsKc5IQ3jdC54D1uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-30T18:23:50Z"
    mac: ENC[AES256_GCM,data:dv1WgZZOfaqCbGN6rpTzuWJloSp0gl0QOmd8eSX3+bTXYMpGteHTp9jXIqNlcM08qN0RGYPyejv9SyHoEip3CgNYPVrv9xWut4kbzlbfAQttWOcHAzsPsxYE+icgPlSQK/7zhJ5a9gh4aJ0FAYq009WVf3uVj3pewt4aAYtg9NU=,iv:z6RNv/HQg/qZfr8hGHIifAt5omRpr16bdGW8Q1iLER8=,tag:+3omsk9LVUvusMzmoZm9uA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
