apiVersion: v1
stringData:
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:/2P/FQVVUgNk4LhHgAdpjXeG3SK8Z7LGAw==,iv:YFbsXyj7zcI6rBESy4+I3EiPPUcQ9xCIUaveQS/dupI=,tag:3Kfo4pbb6UpRYkWygaUXDA==,type:str]
    LDAP_CONFIG_PASSWORD: ENC[AES256_GCM,data:M4S6Y7jTkPjtUaHzNDB7wFKnVEg=,iv:9m9CdUChnCLKXcr/EnKC0vHBmf39pafcZsEHFc5V69Q=,tag:tJ7jmDFQB2I0y7zG+R7vXQ==,type:str]
kind: Secret
metadata:
    name: openldap
    namespace: openldap
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT1JWWDFWY0hIM2g3MXBJ
            SVQ2Mkx0WkE2RWwvU3VYRzk5MHBCSFc2SVVVCm9XOFlOUFg0ckhBcmdSeS9KcFZI
            aklDMlJLdG4zNzZyODM4ajdvbFMxRUUKLS0tIGFPWm5sRnhhMFgrVzdVb0M4dnZJ
            dDdKWENNT3pGb3Z1ZmNmRTF6ZUlMVUUKVgb/7zadiU6GYLcFGXB1+/hPMAM0P4Xf
            kPUVGkOroIkJJ+982qSv0rvbDGlP1Off43p6AtsKc5IQ3jdC54D1uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-30T19:18:07Z"
    mac: ENC[AES256_GCM,data:dy3wj30yp2pS9ufntP1jzqtffaDzAZrcUlnjkviusX/oDrm16+eKPyrgU8Csv6X6a9PNg6XgC+wsuOFGHpKh+SeFEbrujlrpZQG22Y+oa3F+ZywviBPIQ58Yu5YASpizV3hMHM7XOEikNG3jnM24Cb2FBFONVMTUcR7f0uzQaiE=,iv:wx2malVNDEJPbbU67VgxIX+DFXc99ZnvZ+K7Vsvlfmk=,tag:LjNEk8AzxfxxGq3bpOFXbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
