apiVersion: v1
data:
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:XoADGDM3jaGNX66nMc2S60f7UoxtSlPHtw==,iv:jjHex/X3kcbtcUTEfykjPqZr+jBi85ysxEkw+13/zM8=,tag:eCCGpwYOGYhgcUNGazrSjQ==,type:str]
kind: Secret
metadata:
    name: openldap
    namespace: openldap
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT1JWWDFWY0hIM2g3MXBJ
            SVQ2Mkx0WkE2RWwvU3VYRzk5MHBCSFc2SVVVCm9XOFlOUFg0ckhBcmdSeS9KcFZI
            aklDMlJLdG4zNzZyODM4ajdvbFMxRUUKLS0tIGFPWm5sRnhhMFgrVzdVb0M4dnZJ
            dDdKWENNT3pGb3Z1ZmNmRTF6ZUlMVUUKVgb/7zadiU6GYLcFGXB1+/hPMAM0P4Xf
            kPUVGkOroIkJJ+982qSv0rvbDGlP1Off43p6AtsKc5IQ3jdC54D1uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T19:54:14Z"
    mac: ENC[AES256_GCM,data:TN+ntAJVdZ2Uek0sFpQpO4qQgEDq74pwaqu4T1HdVA2Shy06Y5n79tW/WJMWFhKzBss95f2nCrknxVFy1Gun6wPJ6VrQgz3Xuj6K6h0z0NS5uuF4TSm1L7rQkv6A1FcjMo4AOESJBjjWI26jZVLmjYsHHhN7ApleCqIYGCH34J0=,iv:HMz4JfryIqujAWs/cONYLJGn6MVZ6I5tj7JM9Vy9R78=,tag:qpoYVfwG3GS8pGKgw6rxRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
