---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-data-pvc
  namespace: openldap
  labels:
    app.kubernetes.io/instance: openldap
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: openldap
  labels:
    app.kubernetes.io/instance: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: openldap
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:1.5.0
          imagePullPolicy: IfNotPresent
          env:
            - name: LDAP_DOMAIN
              value: jlejeune.home
            - name: LDAP_BASE_DN
              value: dc=jlejeune,dc=home
            - name: LDAP_TLS_CRT_FILENAME
              value: "tls.crt"
            - name: LDAP_TLS_KEY_FILENAME
              value: "tls.key"
            - name: LDAP_TLS_VERIFY_CLIENT
              value: "try"
          envFrom:
            - secretRef:
                name: openldap
          ports:
            - name: openldap
              containerPort: 389
            - name: openldaps
              containerPort: 636
          resources:
            limits:
              memory: 500Mi
          args:
            - '--copy-service'
          volumeMounts:
            - name: ldap-cert-secret
              mountPath: /container/service/slapd/assets/certs
            - name: ldap-data
              mountPath: /var/lib/ldap
              subPath: data
            - name: ldap-data
              mountPath: /etc/ldap/slapd.d
              subPath: config-data
      volumes:
        - name: ldap-data
          persistentVolumeClaim:
            claimName: openldap-data-pvc
        - name: ldap-cert-secret
          secret:
            secretName: openldap-tls
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: openldap
  annotations:
    metallb.io/loadBalancerIPs: ${LB_OPENLDAP_ADDRESS}
spec:
  type: LoadBalancer
  ports:
    - name: openldap
      protocol: TCP
      port: 389
      targetPort: 389
    - name: openldaps
      protocol: TCP
      port: 636
      targetPort: 636
  selector:
    app.kubernetes.io/instance: openldap
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openldap
  namespace: openldap
spec:
  dnsNames:
    - openldaps.jlejeune.home
  issuerRef:
    kind: ClusterIssuer
    name: jlejeune.home
  secretName: openldap-tls
