apiVersion: v1
kind: Secret
metadata:
    name: ldap-admin-secret
    namespace: openldap
type: Opaque
stringData:
    PHPLDAPADMIN_LDAP_HOSTS: ENC[AES256_GCM,data:s9q0r0Tuk9EPIDnM9ETzRA5hiL6hnRosWNqyVfu+MLs4Obvjiv1+0IsJw2O2OVKio+aB9PK/3c6SlqzId/1aD90vy7AhdIKE7FmV7AlsTH/boLCnQymuE1o6oud4q8QWV4vdXBx0EBLhYdIdAS6zfVUn/SV7o0UosMqVdG+F6w==,iv:tIFH8a3H/CsARQ3eg1espQgatxpyUQfsHF/+eJFLxcY=,tag:hBnmC4ah1QqQUEqSDMsd1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cG40ZU1pVlVJdkpKZWtQ
            OXpJQ3VDSEYvMUthc1BDbWZqdm9FNlZIV3pZCmlKUlhleDk2M252Y3psbXFHYllS
            QXJHSEQ1SVdvSCtzUHlZTmFhNkNOYU0KLS0tIG15TXpHMS9IN2x4N0VCejhSYnVZ
            TjZYQXkvTGJOWnRSckpENXl2VHRYQlEKmZ/Nnk0lC2zz1aQ6o0WVWY7+C9RIzR5S
            PR4fuSoWuH8ViQHCB8pAgcZHGPRvRYEKbVuOimTI6Zv7eEnU2TyO+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-25T20:08:22Z"
    mac: ENC[AES256_GCM,data:JME+Jfa99XPvehOwvRzKzBg7YeFowqWrw3l7f4WGQ09gb62eGi3ZENiByPprdFdu7k1LmBfMXVl1XIzZ0+1/vZiN89rEV0zNlC6FQXE108joyUijD3yDhWJ5Ag9tn5XVXzuv+Pas8WE01Oy2nP62DbkS2TSMaTeBJEs2QPFszg0=,iv:dgda794lHQ1iAydhfHddLL5FYOchJrhL4hKX+A6Josk=,tag:Zh8eESVHEpeeUgnZWpU/YA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
