---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: photos
  namespace: networking
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`photos.${SECRET_DOMAIN}`) && PathPrefix(`/photo`)"
      services:
        - kind: Service
          name: photos
          namespace: networking
          port: 443
          scheme: https
    - kind: Rule
      match: Host(`photos.${SECRET_DOMAIN}`)
      middlewares:
        - name: photos-redirectregex
          namespace: networking
      services:
        - kind: Service
          name: photos
          namespace: networking
          port: 443
          scheme: https
  tls:
    secretName: "${SECRET_DOMAIN}-tls"
