---
apiVersion: v1
kind: Service
metadata:
  name: nas
  namespace: networking
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: webdav
  namespace: networking
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5006
