---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: botkube
      version: v0.12.4
      sourceRef:
        kind: HelmRepository
        name: botkube-charts
        namespace: flux-system
      interval: 5m
  values:
    communications:
      discord:
        enabled: true
    serviceMonitor:
      enabled: false  # prometheus is not deployed for now
    config:
      settings:
        clustername: k3s
  valuesFrom:
    - kind: Secret
      name: botkube
      valuesKey: discord_token
      targetPath: communications.discord.token
      optional: false
    - kind: Secret
      name: botkube
      valuesKey: discord_bot_id
      targetPath: communications.discord.botid
      optional: false
    - kind: Secret
      name: botkube
      valuesKey: discord_channel
      targetPath: communications.discord.channel
      optional: false
