---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: botkube
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: botkube
      version: v1.13.0
      sourceRef:
        kind: HelmRepository
        name: botkube-charts
        namespace: flux-system
      interval: 5m
  values:
    communications:
      default-group:
        discord:
          enabled: true
    serviceMonitor:
      enabled: false  # prometheus is not deployed for now
    settings:
      clusterName: k3s
  valuesFrom:
    - kind: Secret
      name: botkube
      valuesKey: discord_token
      targetPath: communications.default-group.discord.token
      optional: false
    - kind: Secret
      name: botkube
      valuesKey: discord_bot_id
      targetPath: communications.default-group.discord.botID
      optional: false
    - kind: Secret
      name: botkube
      valuesKey: discord_channel
      targetPath: communications.default-group.discord.channels.default.id
      optional: false
