apiVersion: v1
kind: Secret
metadata:
    name: botkube
    namespace: monitoring
stringData:
    discord_bot_id: ENC[AES256_GCM,data:q5ui6AoalAeL4BkhKg71Sx84Fw==,iv:6ZeFUSRKEw0eVTI/nF1sOC3KzzwPJqC+rpQmuUZ3B4I=,tag:Pjc4FfYvVnomrTQE4qu0RA==,type:str]
    discord_token: ENC[AES256_GCM,data:zscjyvHTFIsFMzcTV8A4mNRnEcu3lt8uruKG1dJVn64f3ey79mGBrdO2QrhzJQyz/Hr6Z6a1UfgfvLqd2xNyuFrP9ZJ4ZGhR,iv:exYglkOOdVJ0cU2Ca+mWkeF7duqsvF3vamONJ8Flt38=,tag:KfyaSfmbh78N37aoabQQFQ==,type:str]
    discord_channel: ENC[AES256_GCM,data:c9uR1KyBBILy36Gwo8aNui3xhA==,iv:vggbE04Z3pARbCektcXQIGX2Jmwz1CvqAYYGqqGsccg=,tag:kQIV8yx0kctIUy6TPxcMvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v888svjrzkthezatjrvejzelr9r6zuv8sry280k4phuw8p7p4ycstn2ces
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBza0RaQkt5aTU0Ti9WT0Z0
            WDFRMU9NQThDNGhrK2hCMEVrSFowcG8wVUZvClU2b1E3cFF3SnBUNWpNMVVoSU5M
            WkJWYWNhTUl0R2lzN0E4M0ZWcm9NMUkKLS0tIHpiWEMrTFVPSCtQYmNZS3A0UFl6
            ZzZHcm5TY0ViNnZ6WW9XMHNLVzRhZ1EKlzA35vX0SUicFM6hW2wUzMyasNEDKhEv
            aMX7c7kmZYIhH2WwY3qWRJI/7hsrx/B+i1OfYBP+balS+CF/KMeCXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-27T21:52:09Z"
    mac: ENC[AES256_GCM,data:rwD+bg73IVq5GDaEt6Mm1Naw4n03atAhPWTJs1O8v42jD5vXu8JV0zhhJnY1xsURHGj8o2ppI1BQDi9iZZo5oxcogTB+wITEbb4y01SuNEfLXjjsXCNW9L3h85fXo+DzOZOvRVjNBQ0KN2SVjxYRhEKfN/X1I/+KB0n59AP4g0o=,iv:tfWJFAybzs5vc6QP66YtO6HcaGuS+nCS4LiyeKMjJUk=,tag:TEVVR7WknbRHFDLtFwce9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
