---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 0.13.12
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
      interval: 5m
  values:
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - 192.168.1.200-192.168.1.250
    psp:
      create: false
