---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-app
  namespace: flux-system
spec:
  path: ./cluster/core/networking/metallb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
  interval: 60m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-app
  path: ./cluster/core/networking/metallb/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: false
  interval: 60m
  retryInterval: 1m
  timeout: 5m
