---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 60m
  chart:
    spec:
      chart: charts/gitops-server
      sourceRef:
        kind: GitRepository
        name: weave-gitops-charts
        namespace: flux-system
  values:
    adminUser:
      create: true
      passwordHash: ${SECRET_WEAVE_GITOPS_ADMIN_PASSWORD}
      username: admin
