---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: jellyfin
spec:
  storageClassName: longhorn
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app.kubernetes.io/instance: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: jellyfin
    spec:
      restartPolicy: Always
      containers:
        - name: jellyfin
          image: docker.io/jellyfin/jellyfin:10.9.10
          ports:
            - containerPort: 8096
              name: http
          readinessProbe:
            httpGet:
              path: /web/index.html
              port: 8096
            failureThreshold: 5
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: movies
              mountPath: /movies
              readOnly: True
            - name: shows
              mountPath: /shows
              readOnly: True
            - name: transcode
              mountPath: /transcode
            - name: cache
              mountPath: /cache
            - name: config
              mountPath: /config
      volumes:
        - name: movies
          nfs:
            server: ${NAS_ADDRESS}
            path: /volume1/video/films
        - name: shows
          nfs:
            server: ${NAS_ADDRESS}
            path: /volume1/video/series
        - name: transcode
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  ports:
    - port: 8096
  selector:
    app.kubernetes.io/instance: jellyfin
