---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server
  namespace: system-upgrade
spec:
  version: "v1.33.6+k3s1"
  serviceAccountName: system-upgrade
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - { key: node-role.kubernetes.io/control-plane, operator: Exists }
  upgrade:
    image: rancher/k3s-upgrade
