---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-pvc
  namespace: home-automation
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: home-automation
  labels:
    app.kubernetes.io/instance: whisper
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: whisper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: whisper
    spec:
      containers:
        - name: whisper
          image: rhasspy/wyoming-whisper:3.0.2
          args:
            - --model
            - tiny-int8
            - --language
            - fr
          env:
            - name: TZ
              value: {{TZ}}
          ports:
            - name: whisper
              containerPort: 10300
              protocol: TCP
          volumeMounts:
            - name: whisper-data
              mountPath: /data
      volumes:
        - name: whisper-data
          persistentVolumeClaim:
            claimName: whisper-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: whisper
  namespace: home-automation
  annotations:
    metallb.io/loadBalancerIPs: {{LB_WHISPER_ADDRESS}}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: whisper
  ports:
    - protocol: TCP
      name: whisper
      port: 10300
      targetPort: 10300
