---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # NOTE: Only enable system-upgrade-controller if you also update the version of k3s in the following file
  # otherwise if you run ansible against an already provisioned cluster you might downgrade it
  # https://github.com/jlejeune/jlejeune.home-ansible/blob/master/ansible/roles/k3s/defaults/main.yml
  - system-upgrade-controller/ks.yaml
