---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-writer
  namespace: networking
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-writer
rules:
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "delete", "deletecollection", "patch", "update", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-writer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-writer
subjects:
  - kind: ServiceAccount
    name: external-dns-writer
    namespace: networking
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dynamic-dns-operator
  namespace: networking
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: external-dns-writer
          containers:
            - name: dynamic-dns-operator
              image: bitnami/kubectl:1.32
              command:
                - /bin/sh
                - -c
                - |
                  cat << EOF > /tmp/ingress.yml && kubectl apply -f /tmp/ingress.yml
                  apiVersion: networking.k8s.io/v1
                  kind: Ingress
                  metadata:
                    name: ip
                    annotations:
                      external-dns.alpha.kubernetes.io/hostname: '$IP_HOSTNAME'
                      external-dns.alpha.kubernetes.io/target: '$(curl --silent ifconfig.me)'
                  spec:
                    rules:
                      - host: '$IP_HOSTNAME'
                  EOF
              env:
                - name: IP_HOSTNAME
                  value: ${SECRET_DYNAMIC_DOMAIN}
          nodeName: theoden
          restartPolicy: OnFailure
